const LS_KEYS={users:'crm_users_v1',leads:'crm_leads_v1',groups:'crm_groups_v1',settings:'crm_settings_v1',statuses:'crm_statuses_v1',logs:'crm_login_logs_v1',reminders:'crm_reminders_v1'};
const DB_NAME='crm_pro_db',DB_VERSION=1,STORES=['leads','users','groups','statuses','settings','logs','reminders','backups'];
let _db=null;
function openDB(){if(_db)return Promise.resolve(_db);return new Promise((res,rej)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=e=>{const db=e.target.result;STORES.forEach(s=>{if(!db.objectStoreNames.contains(s)){if(s==='backups')db.createObjectStore(s,{keyPath:'id'});else db.createObjectStore(s,{keyPath:'__singleton'});}});};req.onsuccess=e=>{_db=e.target.result;res(_db);};req.onerror=e=>rej(e.target.error);});}
async function idbGet(store){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,'readonly');const req=tx.objectStore(store).get('__singleton');req.onsuccess=()=>res(req.result?.data??null);req.onerror=()=>rej(req.error);});}
async function idbSet(store,data){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');const req=tx.objectStore(store).put({__singleton:'__singleton',data});req.onsuccess=()=>res(true);req.onerror=()=>rej(req.error);});}
async function idbGetAllBackups(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('backups','readonly');const req=tx.objectStore('backups').getAll();req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error);});}
async function idbPutBackup(b){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('backups','readwrite');const req=tx.objectStore('backups').put(b);req.onsuccess=()=>res(true);req.onerror=()=>rej(req.error);});}
async function idbDeleteBackup(id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('backups','readwrite');const req=tx.objectStore('backups').delete(id);req.onsuccess=()=>res(true);req.onerror=()=>rej(req.error);});}
export async function migrateFromLocalStorage(){if(localStorage.getItem('crm_idb_migrated'))return false;let count=0;for(const[store,key]of Object.entries(LS_KEYS)){try{const raw=localStorage.getItem(key);if(raw){await idbSet(store,JSON.parse(raw));count++;}}catch(e){console.warn('Migration:',e);}}localStorage.setItem('crm_idb_migrated',new Date().toISOString());window.dispatchEvent(new CustomEvent('crm:migration-done',{detail:{count}}));return true;}
export async function readAsync(store){try{const d=await idbGet(store);if(d!==null)return d;}catch(e){}try{const r=localStorage.getItem(LS_KEYS[store]);return r?JSON.parse(r):null;}catch(e){return null;}}
export async function writeAsync(store,data){try{await idbSet(store,data);}catch(e){}try{if(LS_KEYS[store])localStorage.setItem(LS_KEYS[store],JSON.stringify(data));}catch(e){}}
export function readSync(key){try{return JSON.parse(localStorage.getItem(key)||'null');}catch(e){return null;}}
export function writeSync(key,val){localStorage.setItem(key,JSON.stringify(val));const store=Object.entries(LS_KEYS).find(([,k])=>k===key)?.[0];if(store)idbSet(store,val).catch(console.warn);}
const BACKUP_INTERVAL_MS=30*60*1000,MAX_INTERNAL_BACKUPS=5;
let _backupTimer=null,_lastBackupTime=null;
export async function createSnapshot(){const s={id:'backup_'+Date.now(),created_at:new Date().toISOString(),version:'1.0',data:{}};for(const store of Object.keys(LS_KEYS))s.data[store]=await readAsync(store);s.summary={leads:(s.data.leads||[]).length,users:(s.data.users||[]).length};return s;}
export async function saveInternalBackup(){const s=await createSnapshot();await idbPutBackup(s);const all=await idbGetAllBackups();all.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));for(const o of all.slice(MAX_INTERNAL_BACKUPS))await idbDeleteBackup(o.id);_lastBackupTime=new Date();window.dispatchEvent(new CustomEvent('crm:backup-saved',{detail:{time:s.created_at}}));return s;}
export function startAutoBackup(){if(_backupTimer)clearInterval(_backupTimer);setTimeout(()=>saveInternalBackup(),5000);_backupTimer=setInterval(()=>{saveInternalBackup().catch(console.error);},BACKUP_INTERVAL_MS);}
export function stopAutoBackup(){if(_backupTimer)clearInterval(_backupTimer);_backupTimer=null;}
export async function downloadBackupJSON(filename){const s=await createSnapshot();const date=new Date().toISOString().slice(0,10);const name=filename||'crm_backup_'+date+'.json';const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);return name;}
export async function getBackupList(){const all=await idbGetAllBackups();return all.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(b=>({id:b.id,created_at:b.created_at,summary:b.summary}));}
export async function restoreFromBackupId(id){const db=await openDB();const bk=await new Promise((res,rej)=>{const tx=db.transaction('backups','readonly');const req=tx.objectStore('backups').get(id);req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});if(!bk)throw new Error('Sauvegarde introuvable');return restoreFromSnapshot(bk);}
export async function restoreFromFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=async e=>{try{const s=JSON.parse(e.target.result);if(!s?.data)throw new Error('Format invalide');await restoreFromSnapshot(s);resolve(s);}catch(err){reject(err);}};r.onerror=()=>reject(new Error('Erreur lecture'));r.readAsText(file);});}
async function restoreFromSnapshot(s){await saveInternalBackup();for(const[store,data]of Object.entries(s.data)){if(data!=null)await writeAsync(store,data);}window.dispatchEvent(new CustomEvent('crm:data-restored',{detail:{from:s.created_at}}));setTimeout(()=>window.location.reload(),500);return s;}
export function getBackupStatus(){return{lastBackup:_lastBackupTime,isRunning:!!_backupTimer};}
export async function initBackupService(){await openDB();await migrateFromLocalStorage();startAutoBackup();}
export default{initBackupService,migrateFromLocalStorage,readAsync,writeAsync,readSync,writeSync,createSnapshot,saveInternalBackup,downloadBackupJSON,restoreFromBackupId,restoreFromFile,getBackupList,getBackupStatus,startAutoBackup,stopAutoBackup};
