import{normalizePhone}from'../utils/phoneNormalizer';
import{readSync,writeSync}from'./BackupService';
const KEY_USERS='crm_users_v1',KEY_LEADS='crm_leads_v1',KEY_GROUPS='crm_groups_v1',KEY_SETTINGS='crm_settings_v1',KEY_STATUSES='crm_statuses_v1',KEY_LOGS='crm_login_logs_v1',KEY_REMINDERS='crm_reminders_v1',MAX_LOGS=500;
const DEFAULT_GROUPS=[{id:'leads',name:'Lead',description:'Prospects à traiter et qualifier',color:'#38bdf8',builtin:true},{id:'data',name:'Data',description:'Contacts et données brutes',color:'#a78bfa',builtin:true}];
const DEFAULT_STATUSES=[{id:'nouveau',label:'Nouveau',color:'#a78bfa',builtin:true},{id:'en_cours',label:'En cours',color:'#38bdf8',builtin:true},{id:'rappel',label:'Rappel',color:'#fb923c',builtin:true},{id:'transforme',label:'Transformé',color:'#34d399',builtin:true},{id:'ne_repond_pas',label:'Ne répond pas',color:'#94a3b8',builtin:true},{id:'refus',label:'Refus',color:'#fb7185',builtin:true}];
function uid(p='id'){return p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,8);}
function read(key){return readSync(key);}
function write(key,val){writeSync(key,val);}
export function initStorage(){let users=read(KEY_USERS)||[];if(!users||users.length===0){users=[{id:uid('u'),email:'admin@crm.fr',password:'admin123',role:'admin',full_name:'Administrateur',active:true},{id:uid('u'),email:'agent@crm.fr',password:'agent123',role:'agent',full_name:'Agent Test',active:true}];write(KEY_USERS,users);}else if(!users.find(u=>u.email==='agent@crm.fr')){users.push({id:uid('u'),email:'agent@crm.fr',password:'agent123',role:'agent',full_name:'Agent Test',active:true});write(KEY_USERS,users);}
const stored=read(KEY_STATUSES);if(!stored){write(KEY_STATUSES,DEFAULT_STATUSES);}else{write(KEY_STATUSES,stored.map(s=>{const d=DEFAULT_STATUSES.find(x=>x.id===s.id&&x.builtin);return d?{...s,color:d.color,label:d.label,builtin:true}:s;}));}
const storedGroups=read(KEY_GROUPS);if(!storedGroups||storedGroups.length===0){write(KEY_GROUPS,DEFAULT_GROUPS);}else{const hasAll=DEFAULT_GROUPS.every(d=>storedGroups.find(g=>g.id===d.id));if(!hasAll)write(KEY_GROUPS,[...DEFAULT_GROUPS.filter(d=>!storedGroups.find(g=>g.id===d.id)),...storedGroups]);}
if(!read(KEY_SETTINGS))write(KEY_SETTINGS,{theme:'dark'});}
export function getUsers(){return read(KEY_USERS)||[];}
export function findUserByEmail(email){return getUsers().find(u=>u.email?.toLowerCase()===email?.toLowerCase())||null;}
export function createUser({email,password,role='agent',full_name}){const users=getUsers();const u={id:uid('u'),email,password,role,full_name,active:true};users.push(u);write(KEY_USERS,users);return u;}
export function updateUser(id,patch){const users=getUsers();const i=users.findIndex(u=>u.id===id);if(i>-1){users[i]={...users[i],...patch};write(KEY_USERS,users);return users[i];}return null;}
export function deleteUser(id){write(KEY_USERS,getUsers().filter(u=>u.id!==id));}
export function changeUserPassword(id,newPassword,actorId){const users=getUsers();const i=users.findIndex(u=>u.id===id);if(i===-1)return null;users[i].password=newPassword;users[i].last_password_changed_at=new Date().toISOString();users[i].history=users[i].history||[];users[i].history.unshift({id:uid('uh'),user_id:actorId||null,action:'password_changed',note:'Mot de passe changé',created_at:new Date().toISOString()});write(KEY_USERS,users);try{localStorage.setItem('crm_force_logout_'+id,String(Date.now()));}catch(e){}return users[i];}
export function loginUser({email,password}){const u=findUserByEmail(email);if(!u||u.active===false||u.password!==password)return null;return{id:u.id,email:u.email,role:u.role,full_name:u.full_name};}
export function getStatuses(){return read(KEY_STATUSES)||DEFAULT_STATUSES;}
export function createStatus({label,color}){const statuses=getStatuses();const id=label.toLowerCase().trim().replace(/s+/g,'_').replace(/[^a-z0-9_]/g,'');if(!id||statuses.find(s=>s.id===id))return null;const s={id,label:label.trim(),color:color||'#8e8e93',builtin:false};statuses.push(s);write(KEY_STATUSES,statuses);return s;}
export function updateStatus(id,patch){const statuses=getStatuses();const i=statuses.findIndex(s=>s.id===id);if(i===-1)return null;statuses[i]={...statuses[i],...patch};write(KEY_STATUSES,statuses);return statuses[i];}
export function deleteStatus(id){const statuses=getStatuses();if(!statuses.find(x=>x.id===id))return false;write(KEY_STATUSES,statuses.filter(x=>x.id!==id));return true;}
export function getGroups(){return read(KEY_GROUPS)||DEFAULT_GROUPS;}
export function createGroup({name,description,color}){const groups=getGroups();const g={id:uid('g'),name,description:description||'',color:color||'#60a5fa',builtin:false};groups.push(g);write(KEY_GROUPS,groups);return g;}
export function updateGroup(id,patch){const groups=getGroups();const i=groups.findIndex(g=>g.id===id);if(i>-1){groups[i]={...groups[i],...patch};write(KEY_GROUPS,groups);return groups[i];}return null;}
export function deleteGroup(id){const groups=getGroups();const g=groups.find(x=>x.id===id);if(!g||g.builtin)return false;write(KEY_GROUPS,groups.filter(x=>x.id!==id));return true;}
export function getLeads(){return read(KEY_LEADS)||[];}
export function findLeadById(id){return getLeads().find(l=>l.id===id);}
function leadHistoryEntry(userId,action,note){const actor=userId?getUsers().find(u=>u.id===userId):null;return{id:uid('h'),user_id:userId||null,user_name:actor?(actor.full_name||actor.email):null,action,note,created_at:new Date().toISOString()};}
export function createLead(data,currentUserId){const leads=getLeads();const l={id:uid('l'),first_name:data.first_name||'',last_name:data.last_name||'',address:data.address||'',city:data.city||'',postal_code:data.postal_code||'',phone:data.phone||'',phone_normalized:normalizePhone(data.phone||''),email:data.email||'',email_lower:(data.email||'').toLowerCase(),status:data.status||'nouveau',source:data.source||'',comment:data.comment||'',group_id:data.group_id||null,assigned_to:data.assigned_to||null,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),history:[leadHistoryEntry(currentUserId,'created','Création manuelle')]};leads.unshift(l);write(KEY_LEADS,leads);return l;}
export function updateLead(id,patch,currentUserId){const leads=getLeads();const i=leads.findIndex(x=>x.id===id);if(i===-1)return null;const old=leads[i];const updated={...old,...patch,updated_at:new Date().toISOString()};const statuses=getStatuses();Object.keys(patch).forEach(k=>{if(k==='comment'){updated.history=updated.history||[];updated.history.unshift(leadHistoryEntry(currentUserId,'comment',String(patch[k])));}else if(k==='status'&&old[k]!==patch[k]){const oL=statuses.find(s=>s.id===old[k])?.label||old[k];const nL=statuses.find(s=>s.id===patch[k])?.label||patch[k];updated.history=updated.history||[];updated.history.unshift(leadHistoryEntry(currentUserId,'status_changed',oL+' → '+nL));}else if(old[k]!==patch[k]){updated.history=updated.history||[];updated.history.unshift(leadHistoryEntry(currentUserId,'updated',k+' → '+String(patch[k])));}});leads[i]=updated;write(KEY_LEADS,leads);return updated;}
export function deleteLead(id){write(KEY_LEADS,getLeads().filter(l=>l.id!==id));}
export function addCommentToLead(id,note,currentUserId){return updateLead(id,{comment:note},currentUserId);}
export function detectDuplicate({email,phone}){const leads=getLeads();const eL=(email||'').toLowerCase();const pN=normalizePhone(phone||'');return{dupEmail:eL?leads.find(l=>l.email_lower===eL):null,dupPhone:pN?leads.find(l=>l.phone_normalized===pN):null};}
export function roundRobinAssign(leadIds=[],agentIds=null,currentUserId=null){const actor=getUsers().find(u=>u.id===currentUserId);if(!actor||actor.role!=='admin')return[];const agents=agentIds?.length?agentIds:getUsers().filter(u=>u.role!=='admin').map(u=>u.id);if(!agents?.length)return[];const settings=read(KEY_SETTINGS)||{};let idx=settings.__last_rr_index||0;const updated=[];leadIds.forEach(lid=>{const agent=agents[idx%agents.length];const res=updateLead(lid,{assigned_to:agent},currentUserId);if(res)updated.push(res);idx++;});settings.__last_rr_index=idx%agents.length;write(KEY_SETTINGS,settings);return updated;}
export function assignLead(leadId,userId,currentUserId){const actor=getUsers().find(u=>u.id===currentUserId);if(!actor||actor.role!=='admin')return null;return updateLead(leadId,{assigned_to:userId},currentUserId);}
export function importCSV(csvText,{groupId=null,source=null,currentUserId=null}={}){const lines=csvText.split(/
?
/).filter(Boolean);if(!lines.length)return{total:0,imported:0,duplicates:0,errors:0};const delim=lines[0].includes(';')?';':',';const headers=lines[0].split(delim).map(h=>h.trim().toLowerCase());let imported=0,duplicates=0,errors=0;const errors_list=[];for(let i=1;i<lines.length;i++){const parts=lines[i].split(delim).map(p=>p.trim());const row={};headers.forEach((h,idx)=>row[h]=parts[idx]||'');const c={first_name:row.first_name||row.prenom||'',last_name:row.last_name||row.nom||'',phone:row.phone||row.telephone||'',email:row.email||row.mail||'',address:row.address||row.adresse||'',city:row.city||'',postal_code:row.postal_code||'',comment:row.comment||row.note||'',source:row.source||source||'',group_id:groupId};const d=detectDuplicate(c);if(d.dupEmail||d.dupPhone){duplicates++;continue;}try{createLead(c,currentUserId);imported++;}catch(e){errors++;errors_list.push({row:i+1,error:e.message});}}return{total:lines.length-1,imported,duplicates,errors,errors_list};}
export function previewCSV(text){const lines=text.split(/
?
/).filter(l=>l.trim());if(!lines.length)return{headers:[],rows:[],mapping:{},preview:[],total:0,unmapped:[]};const delim=lines[0].includes(';')?';':',';const headers=lines[0].split(delim).map(h=>h.trim());const rows=lines.slice(1).map(l=>{const f=l.split(delim);const row={};headers.forEach((h,i)=>row[h]=(f[i]||'').trim());return row;});const aliases={first_name:['prenom','prénom','firstname'],last_name:['nom','name','lastname'],phone:['tel','telephone','mobile','portable'],email:['email','mail','courriel'],address:['adresse','address','rue'],city:['ville','city'],postal_code:['code_postal','cp','zip'],source:['source','origine'],comment:['commentaire','note']};const mapping={};headers.forEach(h=>{const n=h.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9]/g,'_');let matched='';for(const[field,al]of Object.entries(aliases)){if(al.includes(n)||al.includes(h.toLowerCase())){matched=field;break;}}mapping[h]=matched;});return{headers,rows,mapping,preview:rows.slice(0,5),total:rows.length,unmapped:headers.filter(h=>!mapping[h])};}
export function analyzeImport(text,mapping){const lines=text.split(/
?
/).filter(l=>l.trim());if(!lines.length)return{total:0,newLeads:0,internalDups:0,existingDups:0};const delim=lines[0].includes(';')?';':',';const headers=lines[0].split(delim);const rows=lines.slice(1).map(l=>{const f=l.split(delim);const row={};headers.forEach((h,i)=>row[h]=(f[i]||'').trim());return row;});let newLeads=0,internalDups=0,existingDups=0;const sp=new Set(),se=new Set();const fth={};Object.entries(mapping).forEach(([h,f])=>{if(f)fth[f]=h;});rows.forEach(row=>{const phone=(row[fth.phone]||'').replace(/D/g,'');const email=(row[fth.email]||'').toLowerCase().trim();if((phone&&sp.has(phone))||(email&&se.has(email))){internalDups++;return;}if(phone)sp.add(phone);if(email)se.add(email);const d=detectDuplicate({phone:row[fth.phone]||'',email:row[fth.email]||''});if(d.dupPhone||d.dupEmail)existingDups++;else newLeads++;});return{total:rows.length,newLeads,internalDups,existingDups};}
export function importCSVAdvanced(text,{mapping={},groupId=null,status='nouveau',source=null,dupPolicy='skip',currentUserId=null}={}){const lines=text.split(/
?
/).filter(l=>l.trim());if(!lines.length)return{total:0,imported:0,duplicates:0,overwrote:0,errors:0};const delim=lines[0].includes(';')?';':',';const headers=lines[0].split(delim);const rows=lines.slice(1).map(l=>{const f=l.split(delim);const row={};headers.forEach((h,i)=>row[h]=(f[i]||'').trim());return row;});let imported=0,duplicates=0,overwrote=0,errors=0;const errors_list=[];const sp=new Set(),se=new Set();const fth={};Object.entries(mapping).forEach(([h,f])=>{if(f)fth[f]=h;});const g=f=>rows[0]?Object.keys(fth).length?'':'':(f);rows.forEach((row,idx)=>{try{const phone=row[fth.phone]||'';const email=row[fth.email]||'';const pN=phone.replace(/D/g,'');const eN=email.toLowerCase().trim();if((pN&&sp.has(pN))||(eN&&se.has(eN))){duplicates++;return;}if(pN)sp.add(pN);if(eN)se.add(eN);const c={first_name:row[fth.first_name]||'',last_name:row[fth.last_name]||'',phone,email,address:row[fth.address]||'',city:row[fth.city]||'',postal_code:row[fth.postal_code]||'',comment:row[fth.comment]||'',source:row[fth.source]||source||'',status,group_id:groupId};const d=detectDuplicate(c);if(d.dupPhone||d.dupEmail){if(dupPolicy==='skip'){duplicates++;return;}if(dupPolicy==='overwrite'){updateLead((d.dupPhone||d.dupEmail).id,c,currentUserId);overwrote++;return;}}createLead(c,currentUserId);imported++;}catch(e){errors++;errors_list.push({row:idx+2,error:e.message});}});return{total:rows.length,imported,duplicates,overwrote,errors,errors_list};}
export function computeStats({from=null,to=null,agentId=null}={}){const leads=getLeads().filter(l=>{if(agentId&&l.assigned_to!==agentId)return false;if(from&&new Date(l.created_at)<new Date(from))return false;if(to&&new Date(l.created_at)>new Date(to))return false;return true;});const counts={};getStatuses().forEach(s=>{counts[s.id]=0;});leads.forEach(l=>{counts[l.status]=(counts[l.status]||0)+1;});return{total:leads.length,byStatus:counts};}
function parseUA(ua){if(!ua)return{browser:'—',os:'—'};let b='Autre';if(/Edg//.test(ua))b='Edge';else if(/Chrome//.test(ua))b='Chrome';else if(/Firefox//.test(ua))b='Firefox';else if(/Safari//.test(ua))b='Safari';let o='Autre';if(/Windows NT 10/.test(ua))o='Windows 10/11';else if(/Mac OS X/.test(ua))o='macOS';else if(/Android/.test(ua))o='Android';else if(/iPhone|iPad/.test(ua))o='iOS';else if(/Linux/.test(ua))o='Linux';return{browser:b,os:o};}
export function logLogin(userId){const u=getUsers().find(x=>x.id===userId);const ua=navigator.userAgent||'';const{browser,os}=parseUA(ua);const entry={id:uid('log'),user_id:userId,user_name:u?(u.full_name||u.email):'—',user_email:u?.email||'—',user_role:u?.role||'—',browser,os,user_agent:ua,logged_at:new Date().toISOString()};const logs=read(KEY_LOGS)||[];logs.unshift(entry);write(KEY_LOGS,logs.slice(0,MAX_LOGS));}
export function getLogs(){return read(KEY_LOGS)||[];}
export function clearLogs(){write(KEY_LOGS,[]);}
export function getReminders(){return read(KEY_REMINDERS)||[];}
export function createReminder({lead_id,lead_name,lead_phone,agent_id,agent_name,scheduled_at,note=''}){const reminders=getReminders();const r={id:uid('rem'),lead_id,lead_name,lead_phone,agent_id,agent_name,scheduled_at,note,status:'pending',notified_pre:false,notified_main:false,created_at:new Date().toISOString(),done_at:null};reminders.unshift(r);write(KEY_REMINDERS,reminders);return r;}
export function updateReminder(id,patch){const reminders=getReminders();const i=reminders.findIndex(r=>r.id===id);if(i===-1)return null;reminders[i]={...reminders[i],...patch};write(KEY_REMINDERS,reminders);return reminders[i];}
export function deleteReminder(id){write(KEY_REMINDERS,getReminders().filter(r=>r.id!==id));}
export default{initStorage,getUsers,findUserByEmail,createUser,updateUser,deleteUser,loginUser,changeUserPassword,getStatuses,createStatus,updateStatus,deleteStatus,getLeads,findLeadById,createLead,updateLead,deleteLead,addCommentToLead,detectDuplicate,importCSV,importCSVAdvanced,previewCSV,analyzeImport,getGroups,createGroup,updateGroup,deleteGroup,roundRobinAssign,assignLead,computeStats,logLogin,getLogs,clearLogs,getReminders,createReminder,updateReminder,deleteReminder};
